source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'band-up-ios' do
    pod 'Siesta', '1.1.1'
    pod 'Siesta/UI', '1.1.1'
    pod 'KYDrawerController'
    pod 'Socket.IO-Client-Swift', '8.3.3'
    pod 'ActionSheetPicker-3.0', '~> 2.2.0'
    pod 'UICollectionViewLeftAlignedLayout'
    pod 'MARKRangeSlider'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'SwiftLint'
    pod 'Soundcloud'
    pod 'Google/SignIn'
    pod 'FacebookLogin'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Alamofire', '~> 4.4'
end
